codatio/codat-docs

- docusaurus.config.js
> Edit config urls

- .env.example
- docusaurus.config.js
- package-lock.json
- package.json
- src/theme/BlogSidebar/Desktop/index.tsx
- src/theme/DocItem/index.tsx
- src/theme/DocItem/useZendesk.tsx
#14
Added a hook to provide zendesk widget functionality to the docs.
> Added zendesk hook

- docs/introduction/webhooks/core-rules-create.md
- docs/introduction/webhooks/core-rules-types.md
- docs/introduction/webhooks/core-rules-webhooksecurity.md
- sidebars.js
- src/components/global/Api/index.css
- src/styles/components/_table.scss
- Added webhook pages to sidenav
- Fixed formatting on webhook pages
- Fixed styling on tables in darkmode
- Fixed styling on API fonts
> Added webhook pages to sidenav, plus style fixes

- docs/index.mdx
- docusaurus.config.js
- src/styles/components/_code.scss
- src/styles/components/_doc-item.scss
- src/styles/custom.scss
- src/theme/DocItem/useZendesk.tsx
Code was invisible in light mode
> [fix] remove codeblock color

- src/styles/components/_code.scss
> Fix color contrast in codeblock

- .github/CODEOWNERS
- docs/auth-flow/optimize/funnel.md
- docs/auth-flow/optimize/optimize-the-connection-journey.md
- docs/auth-flow/optimize/platform-selection.md
- docs/auth-flow/optimize/privacy.md
- docs/auth-flow/optimize/value-exchange.md
- docusaurus.config.js
- sidebars/bank-feed-api.js
- src/pages/bank-feed-api/index.tsx
> Links to bank feed api ref, misc.

- docs/index.mdx
Don't open these links in new tabs
> Dont open internal links in new tabs

- docs/accounting-api/overview.md
Updated Accounting API overview
> Acctg API Overview page

- docs/sync-for-expenses/configandcategorize.md
Updated description so that it's not repeated twice
> SfE description

- docs/introduction/change-policy.md
- src/styles/components/_navbar.scss
> Hide things in nav on mobile sizes

- docs/bank-feeds-api/overview.md
- sidebars/bank-feeds-api.js
Added xero bank feeds to side nav, removed a random link from text
> Bank feeds api - nav + corrections

- docs/other/developer-resources.md
- docs/other/file-upload.md
- docs/other/portal/account-management.md
- docs/other/portal/companies.md
- docs/other/portal/dashboard.md
- docs/other/portal/developers.md
- docs/other/user-management/adding-users.md
- docs/other/user-management/sso.md
- docs/other/user-management/user-roles.md
- sidebars.js
Updates to Other Guides section - links, styling, redundant content
> other-guides-section-fixes

- docs/auth-flow/authorize-embedded-link.md
- docs/auth-flow/authorize-hosted-link.md
- docs/auth-flow/build/build-your-own-authorization-journey.md
- docs/auth-flow/build/faqs.md
- docs/auth-flow/customize/branding.md
- docs/auth-flow/customize/customize-link.md
Fixed internal links in a few pages in the Authorization flow section.
> Fix links in auth flow

- docs/integrations/accounting/zoho-books/accounting-zoho-books.md
- docs/integrations/accounting/zoho-books/accounting-zohobooks-setup.md
- docs/integrations/accounting/zoho-books/zoho-book-limits.md
Fix some links, fix table and updated some text in the rate limit section 
> Zoho Books updates

- src/styles/components/_images.scss
Tall images are currently squashed
> Auto width on images

- docs/assess/portal/data-integrity.md
- docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-push-bank-transactions.md
> Correct links

- docs/integrations/commerce/square/commerce-square.md
> Remove square a tag

- package-lock.json
- package.json
- src/theme/DocItem/index.tsx
> Add cookie consent popup

- src/styles/components/_blog.scss
> Update blog styles

- docs/sync-for-expenses/sync-process/expense-transactions.md
updated with additional transactiontypes
added additional transaction types for sync for commerce 
- [ / ] New document(s)/updating existing
> added new transactiontypes

- blog/230411-api-keys.md
- blog/230411-deletion-of-data.md
- blog/230411-legacy-bank-account-endpoints.md
Some deprecation dates changed
> Move deprecations from bank holiday

- docusaurus.config.js
> Add redirect logic

- docs/integrations/accounting/freeagent/freeagent-integration-reference.md
- docs/introduction/webhooks/core-rules-types.md
- docs/sync-for-expenses/sync-process/expense-transactions.md
- docs/sync-for-expenses/sync-process/syncing-expenses.md
- docs/using-the-api/errors.md
- docs/using-the-api/managing-companies.md
- docs/using-the-api/optimizing-api-calls.md
- docs/using-the-api/push.md
- docs/using-the-api/querying.md
> Various fixes, e.g. notes, cautions, syntax highlights, etc.

- sidebars/dataModel.js
- src/components/global/Api/index.css
- src/styles/components/_admonition.scss
- src/styles/components/_lists.scss
> Tidying up

- docs/using-the-api/optimizing-api-calls.md
- docs/using-the-api/paging.md
- docs/using-the-api/querying.md
Formatting changes for code tabs and new lines
> API ref changes

- sidebars/assess.js
- sidebars/dataModel.js
Removing from the nav bar for now as the documents are not ready
Hiding Assess Banking pages
> Hiding supplemental data

- docs/integrations/accounting/sage50/accounting-sage50.md
- docs/integrations/accounting/sage50/installing-the-sage-50-connector.md
- docs/integrations/accounting/sage50/pushing-data-to-sage-50.md
- docs/integrations/accounting/sage50/sage-50-requirements.md
- docs/integrations/accounting/xero/xero-faq.md
- docs/integrations/commerce/mollie/commerce-mollie-test.md
- docs/integrations/commerce/mollie/commerce-mollie.md
- docs/integrations/commerce/paypal/commerce-paypal.md
- docs/integrations/commerce/shopify/test-shopify.md
- docs/integrations/commerce/zettle/zettle-integration-reference.md
- sidebars/integrations.js
A few minor fixes to the Markdown in some of the Integrations articles.
Also removes the "Testing your QuickBooks Online integration" from the sidebar because the content is still in draft.
> Fix style issues in the Integrations section

- docs/core-concepts/companies.md
- docs/core-concepts/overview.md
- docs/index.mdx
- docs/introduction/create-account.md
- docs/introduction/first-steps.md
- docs/using-the-api/overview.md
- src/styles/components/_search.scss
> A few changes for go-live

- src/components/global/Api/index.css
> Hiding the send button temporarily from the api ref

- docs/integrations/banking/plaid/banking-plaid.md
> Suggest edit

- docusaurus.config.js
- sidebars.js
> Signpost the new OAS file more

- docusaurus.config.js
Old changelog articles not link to their new equivalent
#136
> 136 changelog links

- docs/introduction/first-steps.md
> Broken link

- docs/integrations/all-integrations.md
- docusaurus.config.js
- sidebars/integrations.js
> Add all integrations page, set up redirects

- docs/integrations/banking/overview.md
Display a list of banking integrations in the banking overview page
> Change banking ints to list

- docs/integrations/accounting/xero/xero-faq.md
> Update to POST Bank Transactions link and links to Codat's schema

- docs/introduction/webhooks/core-rules-types.md
> Tidy up sfc webhook desc

- docs/usecases/bank-feeds.md
> Correct document

- README.md
- docs/core-concepts/companies.md
- docs/core-concepts/overview.md
- docs/index.mdx
- docs/introduction/create-account.md
- docs/introduction/first-steps.md
- docs/using-the-api/overview.md
> correct url for the old docs

- blog/230217-uat-deprecation-dns.md
Added a missing changelog entry
> Missing changelog entry

- docs/other/user-management/user-roles.md
The table on this page hasn't been completed https://docs.codat.io/other/user-management/user-roles
> Issue with user role table

- docs/underwriting/set-up-local-env.md
- sidebars.js
Initial draft for first review and to clarify the details.
> Draft: Set up local environment

- docs/underwriting/introduction.md
- docs/underwriting/process-loan.md
- docs/underwriting/setting-up.md
- docs/underwriting/uw-decision.md
> Draft: UWBG Introduction

- docs/assess/categories/categories.md
- docs/assess/portal/categorization-of-accounts.md
- docs/assess/reports/enhanced-financials-legacy/balance-sheet.md
- docs/assess/reports/enhanced-financials-legacy/financials.md
- docs/assess/reports/enhanced-financials-legacy/profit-and-loss.md
Addressing comments for PR 182
> Addressing comments for PR 182

- src/components/global/Api/index.css
> Borders around api ref

- docs/integrations/bankfeeds/overview.md
- sidebars/integrations.js
> Add bankfeeds integrations ovberview

- docs/integrations/accounting/xero/xero-faq.md
Adds a new FAQ to [Xero FAQs](https://docs.codat.io/integrations/accounting/xero/xero-faq) explaining custom behaviour when pushing negative Direct incomes and Direct costs via the Xero integration.
> Pushing negative direct costs and incomes to Xero

- sidebars/integrations.js
This pull request reorders the articles for Shopify as follows:
- Shopify
- Set up Shopify using custom apps
- Requirements for public apps
- Set up Shopify using public apps
- Test your Shopify integration
> Shopify integration: Move the public app requirements article in the nav

- docs/sync-for-expenses/configandcategorize.md
- docs/sync-for-expenses/gettingstarted.md
- docs/sync-for-expenses/sync-process/sync-process-explained.md
- docs/sync-for-expenses/sync-process/syncing-expenses.md
- docs/sync-for-expenses/sync-process/uploading-receipts.md
Updated base url on docs from expensesync.codat.io to api.codat.io
> updated base url to api.codat.io

- docs/sync-for-expenses/sync-process/expense-transactions.md
- docs/sync-for-expenses/sync-process/sync-process-explained.md
- docs/sync-for-expenses/sync-process/syncing-expenses.md
- docs/sync-for-expenses/sync-process/uploading-receipts.md
- src/styles/components/_admonition.scss
- src/styles/components/_cards.scss
- src/styles/components/_code.scss
- src/styles/components/_tabs.scss
- src/styles/custom.scss
> Style fixes

- docusaurus.config.js
> Configure tracking

- docs/integrations/commerce/stripe/commerce-stripe-setup.md
Stripe Connect setup guide is outdated. There is no need to select platform/marketplace or any pop-up window.
> update steps to set up Stripe Connect

- src/styles/components/_tabs.scss
Minor style change
- Added border radius 4px to tabs content
> Add border radius to tabs

- docs/introduction/create-account.md
Create an Account page renamed, new section on billing added
> #59976 - Include billing calculations

- docs/assess/data-integrity/api-data-integrity.md
> Fix a few broken links in the Assess/ Data Integrity docs

- src/components/page/api/Stoplight/index.tsx
Enabled hide internal endpoints for our api ref.
> Added hide internal

- docs/sync-for-expenses/configandcategorize.md
- docs/sync-for-expenses/gettingstarted.md
- docs/sync-for-expenses/sync-process/sync-process-explained.md
- docs/sync-for-expenses/sync-process/syncing-expenses.md
- docs/sync-for-expenses/sync-process/uploading-receipts.md
Expense routes were updated incorrectly when the base url was switched to api.codat.io, this PR addresses these.
> updated incorrect routes for sfe

- docs/integrations/all-integrations.mdx
> Change to 30+ integrations

- docs/integrations/accounting/overview.md
- src/components/global/Integrations/integrations.js
Some instances were missing a space
> Ensuring clear books always has a space

- docs/core-concepts/companies.md
- docs/introduction/first-steps.md
- docs/using-the-api/managing-companies.md
Adding 'description' to Company creation
[DevOps # 58660](https://dev.azure.com/codat/Codat/_boards/board/t/Technical%20content/Stories/?workitem=58660)
> 58660: Adding 'description' to Company creation

- docs/assess/guides/underwriting/process-loan.md
- docs/assess/guides/underwriting/uw-decision.md
> Underwriting demo links

- docs/introduction/first-steps.md
Styling code snippets in multiple languages as tabs
> First steps guide: code blocks into tabs

- docs/integrations/commerce/amazon-seller-central/amazon-registration-steps.md
Update URL to IAM User, Access Policy & Role
> Update URL to IAM User, Access Policy & Role

- docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
- docs/integrations/accounting/quickbooksdesktop/installing-the-quickbooks-connector.md
- docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
This pull request adds a note to the QuickBooks Desktop documentation.
> QBD: add note about separate admins

- blog/230710-deprecation-companies-metrics.md
Creation of a new changelog entry for the GET /metrics/companies deprecation.
> 230710 Company metrics endpoint changelog

- docs/core-concepts/connections.md
- docs/integrations/accounting/offline-connectors.md
- docs/integrations/accounting/overview.md
- docs/integrations/accounting/sage50/accounting-sage50.md
- docs/integrations/accounting/sage50/installing-the-sage-50-connector.md
- docs/integrations/accounting/sage50/pushing-data-to-sage-50.md
- docs/integrations/accounting/sage50/sage-50-requirements.md
- docs/integrations/accounting/sage50/sage50-multi-company-mode.md
- src/components/global/Integrations/integrations.js
> Sage50 is UKI

- docs/bank-feeds-api/overview.mdx
- docs/sync-for-expenses/overview.md
- src/components/global/Integrations/integrations.js
- Add integration list to bank feeds
- Rework reusability of the integrations list component a bit
> Add bank feeds int list

- src/styles/custom.scss
> Move scroll to top

- docs/index.mdx
- nav.config.js
- src/styles/components/_navbar.scss
- src/theme/EditThisPage/index.js
> Teardown edits

- docs/auth-flow/customize/customize-link.md
- docs/integrations/banking/overview.md
- docs/other/portal/usage-and-billing.md
- Updated Banking overview with details on Link representation
- Updated Link customization with Banking overview details and data type extras
- Fix to the Billing page to confirm relevance for start-up only
> Fix: banking in auth flow and start-up billing

- docs/auth-flow/overview.md
Documenting asynchronous use of Link.
> Async use of Link

- .env.example
- docusaurus.config.js
> Add old ga id

- docs/core-concepts/companies.md
- docs/core-concepts/overview.md
- docs/index.mdx
- docs/introduction/create-account.md
- docs/introduction/first-steps.md
- docs/using-the-api/overview.md
> Removing admonitions referencing our old docs

- docs/assess/guides/underwriting/uw-decision.md
> Fix: Missing bracket

- blog/240101-draft.md
Template change to cover the necessary sections and format
> Changelog template change

- docs/index.mdx
> Fix couple of links

- src/components/global/DataTypes/dataTypes.js
- src/components/global/DataTypes/index.js
- src/components/global/DataTypes/styles.module.scss
- Group reports and begin to clarify the distinction between a true data type (from a source) and a summary of other data types (a report)
- Fix styles
> Fix styles and group reports

- docs/index.mdx
- docs/usecases/overview.md
- src/styles/components/_cards.scss
> Fix styles for cards

- docs/assess/guides/migration-guides/deprecation-account-categories.md
Removed the category version from the title as its internal language
> Remove versions from docs

- blog/20230710-deprecation-v2-categories
- blog/authors.yml
- sidebars/assess.js
Blog post for deprecation + adding docs to nav. Please don't merge - I will do this manually tomorrow
> Assess v2 categories deprecation post

- blog/230710-deprecation-v2-categories.md
> Fix assess deprecation formatting

- docs/integrations/accounting/netsuite/accounting-netsuite-delete-bills-billpayments.md
- docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
- sidebars/integrations.js
This pull request adds a new article on deleting Journal entries from QuickBooks Online.
> QBO - Delete Journal entries

- sidebars/integrations.js
Temporarily hides the new page on Delete Journal entries from QuickBooks Online.
> Edit the integrations sidebar

- sidebars/integrations.js
Adds the new page from #285 to the sidebar.
> Publish the content on deleting Journal Entries from QBO

- src/components/global/Api/index.css
- src/components/global/Api/index.tsx
- src/components/global/Api/styles.module.scss
- src/components/page/api/Stoplight/index.tsx
Making the API ref behave a bit better on mobile
> Adding some responsiveness

- src/components/global/Api/index.css
- src/components/global/Api/index.tsx
- src/components/global/Api/styles.module.scss
> Add mobile menu for api ref

- docs/auth-flow/customize/set-up-redirects.md
- docs/integrations/accounting/myob/accounting-myob-setup.md
- docs/integrations/accounting/myob/accounting-myob.md
- docs/integrations/accounting/overview.md
- sidebars/integrations.js
- src/components/global/Integrations/integrations.js
MYOB Business integration changes
> Refer to MYOB Business

- docs/integrations/commerce/paypal/test-paypal.md
Step three now aligns with the UI a user would see when following these steps.
> Amended steps in line with PayPal UI updates

- docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-new-setup.md
Makes a couple of minor usability changes to the QuickBooks Online setup based on running through the procedure for setting up a sandbox integration.
Adds a horizontal rule after the video walkthrough - the opening sentence is too close at the moment.
Also fixes one broken anchor link. 
> Fixes to Set up QuickBooks Online

- docs/integrations/accounting/netsuite/accounting-netsuite-delete-bills-billpayments.md
> Add links to the API Reference and shorten the title in side nav

- docs/usecases/summary/automating-payables.md
Adds a missing word and fixes a typo on the "Automating payables" landing page.
> Minor edits to automating payables

- docs/sync-for-expenses/sync-process/uploading-receipts.md
Sync for Expenses now supports uploading receipts for netsuite, this change provides the supported formats.
> added netsuite doc format

- redirects.config.js
- added redirect for TrueLayer portal link https://docs.codat.io/redirects/integrations/banking/upvr
> fix truelayer link

- docs/integrations/accounting/quickbooksonline/accounting-quickbooksonline-delete-journal-entries.md
Updating delete Journal Entries page to single page covering all QBO delete functionality across JEs, Bills and Invoices.
- [x ] New document(s)/updating existing
> Created single page for deleting QBO objects

- docs/auth-flow/customize/set-up-webhooks.md
- docs/auth-flow/customize/use-openid-connect.md
Fixed a couple of link fixes caused by double `(` characters. Searched the project to check for any other occurances.
> Couple of link fixes

- docs/integrations/banking/plaid/banking-plaid.md
Description added for Instant Auth and Instant Match supported in the Plaid integration.
> Instant Auth and Instant Match note

- docs/usecases/summary/automating-payables.md
- docs/usecases/summary/automating-receivables.md
- docs/usecases/summary/dashboarding.md
- docs/usecases/summary/integrating-commerce-data.md
- docs/usecases/summary/lending.md
- docs/usecases/summary/managing-expenses.md
- docs/usecases/summary/reconciling-bank-transactions.md
- src/components/global/Usecases/index.js
Fixing typos, corrections, American English in use case pages and components
> Use case fast follow corrections 

- docs/auth-flow/customize/set-up-redirects.md
> Refine redirects settings pages

- blog/230404-product-update-4.md
- docs/auth-flow/customize/set-up-redirects.md
> Fix redirects page, fix updates page types

- docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup.md
> Update links from Swagger to OAS

- src/theme/DocItem/Vote/index.js
- src/theme/DocItem/Vote/styles.module.scss
- Improving styling of vote section
- If negative feedback is given, encourage raising of an issue
> Improve vote styling, encourage feedback for back feedback

- blog/230411-api-keys.md
- blog/230411-deletion-of-data.md
- blog/230411-legacy-bank-account-endpoints.md
Updating post titled to reflect deprecations being complete
> Update post titles

- docs/sync-for-expenses/sync-process/uploading-receipts.md
Link resulted in a 404 page but should have taken the user to https://docs.codat.io/sync-for-expenses-api#/operations/upload-attachment
> Fixing upload attachment link

- docs/integrations/commerce/chargify/commerce-chargify.md
Corrects a few naming errors on the page.
> Fix names and links

- docs/sync-for-expenses/sync-for-expenses-faq.md
Added 3 additional FAQs to the bottom of the list
> Adding to sync-for-expenses-faq.md

- docs/introduction/first-ten-minutes.md
- sidebars.js
- src/components/global/LocalStorageChecklist/index.js
/introduction/first-ten-minutes
Thoughts?
> Example of what the video guides might look like

- docs/bank-feeds-api/overview.mdx
- docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-use.md
- docs/integrations/accounting/xero/xero-faq.md
Fixes a few links to [Create bank transactions](https://docs.codat.io/accounting-api#/operations/create-bank-transactions).
> Fix links to Create bank transactions endpoint

- docs/integrations/commerce/stripe/commerce-stripe-setup.md
Tiny change after checking the docs against the Stripe UI.
Removes a misleading sentence about being asked to create a connected account. Changed to caution format instead.
> Minor edit to Set up the Stripe integration

- docs/introduction/office-hours.md
Fixes to the office hours page
> Fixes to the office hours page

- src/components/global/Api/index.css
> Remove duplicate list markers, fix table styles

- sidebars.js
> Adding sidebar items back in

- docs/guides/bill-pay/how-the-demo-app-works.md
- docs/guides/bill-pay/introduction.md
- docs/guides/bill-pay/run-demo-app-locally.md
- docs/guides/bill-pay/use-bill-pay-demo-app.md
- docs/guides/loan-qualification/introduction.md
- docs/guides/loan-qualification/process-loan.md
- docs/guides/loan-qualification/setting-up.md
> Fix links in guides post-moving guides

- docs/introduction/office-hours.md
> Changed office hours to 30 minues

- nav.config.js
- src/styles/components/_navbar.scss
- src/theme/NavbarItem/DropdownNavbarItem.js
- Remove forum from nav first level
- Tidy up nav dropdown UI - HRs
> Removing duplicate forum, tidying up hrs

- docs/auth-flow/optimize/funnel.md
- docs/auth-flow/optimize/monitor-auth-flow.md
- docs/auth-flow/optimize/optimize-the-connection-journey.md
- docs/auth-flow/optimize/platform-selection.md
- docs/auth-flow/optimize/privacy.md
- docs/auth-flow/optimize/value-exchange.md
Optimize auth flow refinements
- Improving navigation
- Sort headers
- Read next
- Clarify monitoring flow logic if not using Link
> Optimize auth flow refinements

- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral-setup.md
Documents the D365 Business Central license / subscription that is needed to use our integration. 
Please give any feedback on the use of "before you begin" instead of "prerequisites" in the integrations docs.
> Dynamics 365: Document license requirement

- docs/usecases/summary/automating-payables.mdx
updated the payables page - changed some of the text and added feature cards.
`/usecases/summary/automating-payables`
> updated overview page for payables

- docs/integrations/accounting/xero/xero-sign-up-flow.md
Sign up with Xero - Xero video embed
> Sign up with Xero - Xero video embed

- README.md
> Remove beta note

- static/oas/Codat-Bank-Feeds.json
- static/oas/Codat-Banking.json
- static/oas/Codat-Bill-Pay.json
- static/oas/Codat-Commerce.json
- static/oas/Codat-Common.json
> Merged PR 64128: Actual fix

- vercel.json
Allow CORS so the portal can access the RSS feed for product updates
> Allow CORS for RSS feed

- static/oas/Codat-Bank-Feeds.json
> Merged PR 64184: Fixed proxy name

- docs/introduction/first-steps.md
Added python, typescript and go code snippets to first steps.
> Added client libraries code snippets to first steps.

- static/oas/Codat-Bank-Feeds.json
> Merged PR 64393: Updated proxy endpoint from get to post for bank feeds

- docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup.md
> Test client minor fix

- static/oas/Codat-Assess.json
- static/oas/Codat-Common.json
> Merged PR 64431: Renaming alerts

- static/oas/Codat-Common.json
> Merged PR 64451: Readded get sync settings

- docs/using-the-api/rate-limits.md
A little bit of detail about the responses that will be returned.
> add some deails about the rate limiting response to the docs

- static/oas/Codat-Bank-Feeds.json
> Merged PR 64504: Fixed create bank account transactions schemas

- blog/231009-deprecation-webhooks-new-company-synchronized.md
- blog/authors.yml
Add entry for the deprecation of the behaviour of the 'New company synchronized' webhook. 
> add entry for deprecation re: new company synchronized webhook

- static/oas/Codat-Assess.json
- static/oas/Codat-Bank-Feeds.json
- static/oas/Codat-Banking.json
- static/oas/Codat-Bill-Pay.json
- static/oas/Codat-Commerce.json
> Merged PR 64772: Minor change: modifiedDate example

- docs/index.mdx
Adding Bank Feeds API and SfE to the homepage
> Homepage edits

- docs/using-the-api/modified-dates.md
- docs/using-the-api/optimizing-api-calls.md
Aligning the recommendations on use of modified dates, and additional improvements to the pages:
/using-the-api/optimizing-api-calls
/using-the-api/modified-dates
> Modified dates

- docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
- docs/integrations/accounting/sage50/sage-50-requirements.md
Updated Sage 50 and QBD installation documentation to accurately reflect the firewall allow list requirements
- New document(s)/updating existing
> Added more firewall allow list suggestions

- docusaurus.config.js
> switch typesense account

- docs/auth-flow/customize/set-up-redirects.md
> Remove misleading reserved query parameter redirect note

- docs/auth-flow/customize/set-up-redirects.md
Auth flow redirect URLs styling fix
> Auth flow redirect URLs

- docusaurus.config.js
Updated search url as we are going to use a new typesense cluster
> update search url

- docs/assess/guides/migration-guides/deprecation-account-categories-excel.md
> Remove banking report reference

- static/oas/Codat-Bank-Feeds.json
- static/oas/Codat-Common.json
- static/oas/Codat-Expenses.json
- static/oas/Codat-Sync-Commerce.json
OAS files last updated at 2023-06-22 14:59:08
> Latest Open API Specification

- src/styles/components/_scrollbar.scss
> Fix scrollbar contrast

- src/styles/components/_blog.scss
> Fix blog h2 size

- sidebars.js
> Fix sidebars styling for automating bill pay

- src/components/global/Api/index.css
> API ref section spacing

- src/components/global/Integrations/index.tsx
- src/components/global/Integrations/integrations.js
- src/components/global/Integrations/styles.module.scss
- src/styles/components/_labels.scss
- src/styles/custom.scss
> Change labels styling, render multiple tags for integrations/

- src/components/global/Api/index.css
> Fix list markers at depth in api ref

- src/components/global/Api/index.css
> Change dark-mode colours

- src/styles/components/_images.scss
> Borders on images

- docs/guides/invoice-finance/setting-up.md
- docs/guides/loan-qualification/setting-up.md
- docs/introduction/webhooks/core-rules-create.md
- docs/introduction/webhooks/core-rules-webhooksecurity.md
- docs/introduction/webhooks/receive-webhooks-as-email.md
Updates to paths and links that refer to webhooks that now moved into Settings
> Webhooks links update

- blog/231115-put-bank-feed-bank-accounts.md
- blog/authors.yml
Update announcing the deprecationof the PUT bankFeed accounts and adding @DaveHCodat as a contributing author.
> announcement of the deprecation of put for bankfeed bank accounts

- src/styles/components/_blog.scss
> Fix update header sizes

- sidebars/assess.js
Add new enhanced loans and update menu to point to OAS documentation (for which a PR has already been raised)
> Assess add loans endpoint

- docs/integrations/accounting/netsuite/company-linking-journey.md
- docs/integrations/accounting/netsuite/oracle-netsuite-faq.md
- docs/usecases/bill-pay/payments.md
- sidebars/integrations.js
> Correct casing of NetSuite

- docs/using-the-api/querying.md
- Include all operators in table
- Document encoding
> Update querying to document all key operators and encoding

- docs/sfc/sync-for-commerce-knowledge-base/monitoring-a-sync.md
Typo in sync for commerce docs.
> Fixed typo in sync for commerce docs

- docs/introduction/webhooks/core-rules-types.md
Bringing docs back in line with the response sent with the body of the webhook rather than the response from querying the API
Updating response examples to PascalCase so they are consistent with the body of the webhook
> PascalCase

- blog/231010-deprecation-onprem-erp-premium.md
> Remove further confusion

- docs/sync-for-expenses/configandcategorize.md
Added in new copy and an embedded table
> Update configandcategorize - supplier override.md

- blog/231010-journal-entries-contra.md
Also amended datatype to reflect supported datatypes for QBO
Update to note this is only for QBO and change journals to journal entries
> Update change log to indicate integration

- docs/introduction/create-account.md
> Enterprise features

- blog/230710-deprecation-v2-categories.md
> Add update banner and changed date

- docs/using-the-api/queueing-data-syncs.md
Data freshness pitfall update 
> Data freshness pitfall update

- docs/sync-for-expenses/sync-process/uploading-receipts.md
Fixing a spelling mistake in the documentation
> Update uploading-receipts. Spelling mistake.md

- docs/sync-for-expenses/sync-process/updating-expenses.md
Making sure it states what transaction types can be updated
> Xero updating expenses fix.md

- docs/sync-for-expenses/sync-process/expense-transactions.md
> Update expense-transactions- ContactRef.md

- docs/using-the-api/queueing-data-syncs.md
> Some follow-ups on data freshness

- docs/auth-flow/authorize-embedded-link.md
> Embedded link edits

- blog/230731-deprecation-qbd-certificate-update.md
Updated deprecation notice to be more specific about the timings of the required action.
New document(s)/updating existing
> Updated deprecation notice to be more specific around timing

- docs/using-the-api/modified-dates.md
- docs/using-the-api/querying.md
- docs/using-the-api/queueing-data-syncs.md
Added isDeleted property to:
* [Querying](https://docs.codat.io/using-the-api/querying)
* [Refresh company data](https://docs.codat.io/using-the-api/queueing-data-syncs)
* [Using modified dates](https://docs.codat.io/using-the-api/modified-dates)
> Adding isDeleted property

- docs/assess/troubleshooting.md
- docs/core-concepts/connections.md
- docs/core-concepts/integrations.md
- docs/integrations/accounting/quickbooksonline/faq-quickbooks-online.md
Minor changes to multiple pages to cover items raised by support.
> Questions raised to support

- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral.md
- docs/integrations/accounting/netsuite/accounting-netsuite.md
- docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
- docs/integrations/accounting/sage-intacct/accounting-sage-intacct-setup.md
- docs/integrations/accounting/sage50/accounting-sage50.md
- src/styles/components/_cards.scss
> Add premium badge on integration overviews

- docs/sync-for-expenses/sync-process/sync-process-explained.md
> Update sync-process-explained - mermaid diagram update.md

- docs/using-the-api/rate-limits.md
- docs/using-the-api/webhooks/core-rules-types.md
Update the rate limiting docs to include all of the actual limits and remove the piece about logging and give a date for blocking.
> Feature rate limiting docs

- docs/sync-for-expenses/sync-process/sync-process-explained.md
> Update sync-process-explained - queuing syncs.md

- docs/sync-for-expenses/gettingstarted.md
fix datatype table
/sync-for-expenses/gettingstarted
> fix Other useful data types table

- docs/sync-for-expenses/configandcategorize.mdx
> Update configandcategorize - supplier docs.mdx

- docs/auth-flow/overview.md
Final DevEx teardown ticket for Link best practices
> Link best practices

- docs/assess/excel/enhanced-financials-report.md
- docs/data-model/accounting/accounting.md
- docs/data-model/banking/banking.md
- docs/data-model/commerce/commerce.md
In response to feedback-documentation, fixing broken Assess links and missing data model sidebars
> Fix: sidebars and links

- docs/using-the-api/webhooks/core-rules-types.md
> Rate limit rule text

- docs/using-the-api/testing.md
Updated zoho books link to go to their pricing page
Updated zoho books link to go to their pricing page, the existing link goers to their subscriptions API docs which is not relevant
> Updated zoho books link to correct page

- docs/sync-for-expenses/sync-for-expenses-faq.md
> Update sync-for-expenses-faq - adding sections.md

- docs/integrations/accounting/xero/accounting-xero-setup.md
Informs users about the limitation on installation account fo Xero, if they plan to link multiple companies in Xero.
- [X ] New document(s)/updating existing
> Text update for Xero account requirements

- docs/sync-for-expenses/sync-process/expense-transactions.md
> Update expense-transactions Contact Ref example.md

- static/oas/Codat-Assess.json
- static/oas/Codat-Bank-Feeds.json
- static/oas/Codat-Banking.json
- static/oas/Codat-Commerce.json
- static/oas/Codat-Common.json
- static/oas/Codat-Files.json
- static/oas/Codat-Sync-Commerce.json
- static/oas/Codat-Sync-Expenses.json
Updated OAS at 2023-08-22T14:16:54Z
> Automated PR created by OAS bot

- docs/using-the-api/authentication.md
> Fixed uris to api ref

- docs/lending/enhanced-financials/overview.md
- docs/lending/enhanced-invoices/overview.md
- docs/lending/enhanced-liabilities/overview.md
> Additional corrections

- docs/lending/enhanced-cash-flow/overview.md
- docs/lending/enhanced-financials/overview.md
- docs/lending/enhanced-invoices/overview.md
- docs/lending/enhanced-liabilities/overview.md
- sidebars.js
- sidebars/lending.js
> Removing enhanced where not necessary

- docs/configure/portal/companies.md
- docs/configure/portal/pull-and-push-history.md
- docs/integrations/accounting/overview.md
- docs/integrations/banking/basiq/test-your-basiq-integration.md
- docs/integrations/banking/overview.md
- docs/integrations/banking/truelayer/test-truelayer.md
- docs/integrations/commerce/mollie/commerce-mollie-test.md
- docs/integrations/commerce/overview.md
- docs/integrations/commerce/prestashop/test-prestashop.md
- docs/integrations/commerce/shopify/test-shopify.md
- docs/integrations/commerce/square/test-square.md
- docs/integrations/commerce/stripe/test-stripe.md
- docs/integrations/commerce/sumup/test-sumup-1.md
- docs/integrations/commerce/woocommerce/test-woocommerce.md
- docs/integrations/commerce/zettle/test-zettle.md
- docs/using-the-api/pull-history.md
Some menu path changes to align with the new Portal menu structure
> Menu path changes

- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral-setup.md
Updating prerequisites for MS Dynamics to cover a scenario raised by clients in Zendesk tickets.
> Reflecting Zendesk info

- docs/expenses/config-and-categorize.mdx
> Update config-and-categorize - FX management.mdx

- docs/get-started/developer-resources.md
- docs/get-started/libraries.md
Attempt to improve searchability of client libraries when clients search SDK.
> Improve search fro client libraries when someone searches SDKs

- src/components/global/Prototypes/Payroll.js
- src/components/global/Prototypes/styles.module.scss
> Improved example code

- docs/bank-feeds/overview.mdx
- docs/commerce/overview.md
- docs/expenses/overview.md
- docs/payables/overview.mdx
- docs/payroll/overview.mdx
- src/components/global/Integrations/index.tsx
- src/components/global/Integrations/integrations.js
- src/components/global/Integrations/styles.module.scss
> New component

- docs/usecases/summary/managing-expenses.mdx
Removed TODO and added ticket to devops.
> Removed todo

- docs/lending/features/accounts-payable-overview.md
- docs/lending/features/bank-statements-overview.md
- docs/lending/features/financial-statements-overview.md
- docs/lending/overview.md
Minor changes addressing comments for Lending pages
> Lending: addressing comments

- blog/230912-csharp-library-released.md
Release note on C# client library release.
> Product update csharp release

- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral.md
Updating the latest supported version for Dynamics 365 Business Central as users using the older versions wouldn't be able to use our integration
> Update latest supported version for Dynamics 365 BC

- docs/lending/get-started.md
Adding the mention of Link to Lending API
> Lending: auth flow

- docs/bank-feeds/guides/bank-feeds-tutorial.md
- docs/core-concepts/connections.md
- docs/get-started/first-steps.md
- docs/using-the-api/paging.md
- docs/using-the-api/querying.md
> Addded code snippets in all supported languages

- docs/configure/user-management/user-roles.md
* Updating the user role permission tick box grid to include 'View company data' permission for the Onboarding user type. This reflects the current configuration of the service.
- New document(s)/updating existing
> Updating the permissions of the Onboarding user role

- docs/core-concepts/companies.md
- src/styles/components/_read-next.scss
- src/styles/custom.scss
Have tried to do it in as simple a way as possible
> Style read next lists

- docs/using-the-api/webhooks/core-rules-types.md
> Fixed webhook schemas and added missing webhook

- blog/230919-deprecation-link-sdk.md
> Added deprecation notice for link-sdk

- docs/bank-feeds/mapping/codat-ui.md
> Fix broken link

- docs/using-the-api/best-practices/client-side-data-storage.md
> Fix typo in Update client-side-data-storage.md

- docs/lending/guides/general-loan-writeback.md
- src/components/global/Prototypes/Payroll.js
- src/components/global/Prototypes/WritebackMapping.js
Loan writeback guide. Possible future improvements: changing the mapping UI mockup and amending code for source and target accounts.
> Loan writeback guide

- docs/lending/get-started.md
Minor additions to the Lending API Get started page
> Lending API improvements

- src/components/global/Integrations/integrations.js
Fix integration links in component
> Fix integration links in component

- src/components/global/Integrations/integrations.js
> fixing integration names

- docs/lending/guides/loan-qualification/introduction.md
- docs/lending/guides/loan-qualification/process-loan.md
- docs/lending/guides/loan-qualification/setting-up.md
- docs/lending/guides/loan-qualification/uw-decision.md
- docs/usecases/summary/lending.mdx
> Pzaichkina patch 1

- docs/integrations/bank-feeds/qbo-bank-feeds/qbo-bank-feeds-setup.md
- docs/integrations/bank-feeds/sage-bank-feeds/sage-bank-feeds-setup.md
- docs/integrations/bank-feeds/xero-bank-feeds/xero-bank-feeds-setup.md
Removing references to POSTing a list of bankAccounts, replaced with correct description of POSTing individual accounts
> Remove refs to posting list of bank accounts

- docs/using-the-api/push.md
> Missing new line

- docs/bank-feeds/overview.mdx
- docs/terms/bank-feed.md
Taken from chatgpt - feel free to edit the content
cc @jmyorston
> Add bank feed to glossary

- docs/configure/create-account.md
> Remove SAML SSO from being included in full access

- docs/expenses/faq.md
Sentence didn't flow well before
> Update faq - SFE.md

- blog/231026-netsuite-bundle-update.md
- blog/authors.yml
> NetSuite Bundle update blog post

- docs/lending/guides/loan-writeback/configure.md
> Added call out to offer customers the option to enable/disable loan writeback

- docs/expenses/config-and-categorize.mdx
Now able to cover credit and pre pay for Netsuite
> Update config-and-categorize - Netsuite pre pay.mdx

- docs/get-started/libraries.md
> Added library versioning

- docs/payables/bills.md
> correct to accounts payable

- docs/using-the-api/supplemental-data/overview.md
Remove references to update and delete
> remove update references from supplemental data

- docs/bank-feeds/overview.mdx
- docs/lending/overview.md
Client library details to product overviews
> Adding client libraries

- docs/expenses/sync-process/expense-transactions.md
Added in line to expense endpoint for dynamics drafted state
> Update expense-transactions - drafted state endpoint updates.md

- docs/expenses/config-and-categorize.md
1. Changed to md from mdx. 
2. Updated links and advise for creating bank accounts
> Update and rename config-and-categorize.mdx to config-and-categorize.md

- docs/bank-feeds/create-account.md
- docs/bank-feeds/integrations/qbo/mapping.md
- docs/bank-feeds/mapping/api-mapping.md
- docs/bank-feeds/overview.mdx
- docs/bank-feeds/pushing-transactions.md
- docs/bank-feeds/setup.md
- docs/get-started/libraries.md
- src/components/global/ClientLibraries/index.tsx
> Bank feeds code snippets

- docs/payables/payments.md
Delete bills and payments in Sync for Commerce
> Adding delete bills

- docs/bank-feeds/setup.md
- docs/lending/features/accounts-payable-overview.md
- docs/lending/features/accounts-receivable-overview.md
- docs/lending/features/bank-statements-overview.md
- docs/lending/features/company-info-overview.md
- docs/lending/features/excel-download-overview.md
- docs/lending/features/financial-statements-overview.md
- docs/lending/features/liabilities-overview.md
- docs/lending/features/sales-overview.md
- docs/lending/get-started.md
- docs/lending/overview.md
- src/components/global/ClientLibraries/index.tsx
> Added code snippets to lending

- docs/enterprise/tech-overview/security/sso.md
* Add guide for clients to set up enterprise SSO.
- [ x] New document(s)/updating existing
-
> Add enterprise sso content

- docs/get-started/libraries.md
> Added support note to client libraries section

- docs/configure/plans/products-and-services-descriptions.md
> Fixed todo links

- docs/bank-feeds/overview.mdx
> Fixed link

- docs/expenses/sync-process/uploading-receipts.md
> Update uploading-receipts-making multidoc upload more obvious.md

- docs/bank-feeds/create-account.md
- docs/payables/bills.md
- docs/payables/configure-customer.md
- docs/payables/get-started.md
- docs/payables/mapping.md
- docs/payables/overview.mdx
- docs/payables/payments.md
- docs/payables/suppliers.md
> Payables - added code snippets

- docs/integrations/banking/truelayer/faqs-about-truelayer.md
https://dev.azure.com/codat/Codat/_workitems/edit/71468
> Remove Bank of Ireland warning banner

- docs/bank-feeds/guides/bank-feeds-tutorial.md
- docs/core-concepts/companies.md
- docs/using-the-api/managing-companies.md
> Added groups

- docs/core-concepts/companies.md
- docs/using-the-api/managing-companies.md
> More context on groups feature

- docs/expenses/sync-process/syncing-expenses.md
- docs/using-the-api/webhooks/core-rules-types.md
- static/oas/Codat-Expenses.json
- static/oas/Codat-Sync-Expenses-v1.json
- static/oas/Codat-Sync-Expenses.json
> Changed webhook info for SfE

- docs/expenses/config-and-categorize.md
- docs/expenses/faq.md
- docs/expenses/fx-management.md
- docs/expenses/sync-process/expense-transactions.md
- sidebars/sync-for-expenses.js
> Sync for Expenses: FX management

- docs/integrations/accounting/quickbooksdesktop/installing-the-quickbooks-connector.md
- docs/integrations/accounting/quickbooksdesktop/legacy/installing-the-quickbooks-connector.md
- docs/lending/guides/invoice-finance/inv-fin-decision.md
- docs/lending/guides/invoice-finance/setting-up.md
- docs/lending/guides/loan-qualification/setting-up.md
- docs/lending/guides/loan-qualification/uw-decision.md
Removing html checkboxes due to styling issues
> Removing checkboxes

- docs/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements.md
Updated docs about supported environments for QBD to better explain issue that users may encounter with unsupported setups
> Updating QBD support environment docs

- docs/expenses/config-and-categorize.md
- docs/expenses/configure-customer.md
- docs/expenses/fx-management.md
- docs/expenses/overview.md
- docs/expenses/sync-process/expense-transactions.md
- docs/expenses/sync-process/uploading-receipts.md
- sidebars/sync-for-expenses.js
- src/components/global/Integrations/integrations.js
> Adding QBD link.js

- blog/240223-java-library-released.md
- src/components/global/ClientLibraries/index.tsx
> Library versioning update

- src/pages/sync-for-partner-commerce-api/index.tsx
- static/oas/Codat-Sync-Partner-Commerce.json
> Added hidden api ref.

- docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-troubleshooting.md
* I've added 2 sections to the Troubleshooting page on scenarios where the web connector will not be running and scenarios where QBD won't open. They are a little similar to the [Limitations](https://docs.codat.io/integrations/accounting/quickbooksdesktop/software-and-hardware-requirements#limitations) section on the Requirements page, but I think they are helpful. Happy to be told otherwise / it changed.
> Update to quickbooks-desktop-troubleshooting.md

- docs/using-the-api/paging.md
Included some new text on the paging page to reference our recommended page size with a link to the optimization page.
> Added some extra text for optimizing API responses

- blog/240319-deprecation-ruleId.md
- blog/240320-deprecation-ruleId.md
- docs/using-the-api/webhooks/migration-guide-advanced.md
> Added ruleId deprecation notice

- src/pages/supplier-enablement-api/index.tsx
- static/oas/Codat-Supplier-Enablement.json
> Supplier enablement oas

- docs/integrations/accounting/netsuite/oracle-netsuite-integration-reference.md
We now support refunding a credit note on NetSuite, so removing the disclaimer from the docs as per this thread https://teamcodat.slack.com/archives/C01GTD5TXG8/p1711356389559429
> NetSuite - support credit note refunds

- docs/expenses/sync-process/reimbursable-expense-transactions.md
> Reimbursement updates

- src/pages/intuit-idx-api/index.tsx
> Added intuit API ref

- docs/expenses/overview.md
> Adding QBD to reimbursement and transfers.md

- docs/integrations/accounting/exact-online/accounting-exact-setup.md
Adds additional scope of costcenters  
> Add costcenters scope under financials

- docs/using-the-api/webhooks/zapier-integration.md
> Added callout about multi-user limitations.

- src/pages/bank-feeds-v2-api/index.tsx
- static/oas/Codat-Bank-Feeds-v2.json
> Added Bank Feeds v2 API ref. (hidden)

- blog/240505-new-webhook-zapier-integration.md
- docs/using-the-api/webhooks/zapier-integration.md
> Updated Zapier page following app approval

- docs/expenses/config-and-categorize.md
> Remove config from sfe

- docs/integrations/banking/plaid/faqs-plaid.md
- sidebars/integrations-banking.js
Adding the Plaid FAQs back in and adding a section on the error we've seen from Chase
> Plaid FAQs

- src/theme/BlogLayout/index.tsx
- src/theme/DocPage/index.tsx
> Staging copy

- src/components/global/Integrations/integrations.js
> Adding in QBO - Update integrations.js

- docs/configure/create-account.md
Updating company limit to reflect new levels
> Update company limit

- docs/supplier-enablement/guides/analyze-spend.md
- docs/supplier-enablement/guides/manage-relationships.md
- docs/supplier-enablement/guides/refresh-data.md
- sidebars/supplier-enablement.js
> RM Portal link change

- .github/workflows/linknator.yml
- blog/220817-product-update.md
- docs/index.mdx
- docs/support/get-help.mdx
> Add filtering to the linknator script

- blog/220714-support.md
- blog/220817-product-update.md
- blog/220817-qbd-refs.md
- blog/230404-product-update-4.md
- blog/230414-product-update-5.md
- blog/230428-April-Features.md
- blog/230530-may-updates.md.off
- blog/230630-june-updates.md.off
- blog/230710-deprecation-v2-categories.md
- blog/240306-new-webhook-service-released.md
- docs/auth-flow/optimize/connection-management.md
- docs/bank-feeds/integrations/qbo/mapping.md
- docs/bank-feeds/integrations/sage/mapping.md
- docs/integrations/accounting/xero/xero-app-partner-program.md
- docs/lending/excel/audit-report.md
- docs/lending/excel/enhanced-cash-flow-report.md
- docs/lending/excel/enhanced-financials-report.md
- docs/lending/excel/enhanced-invoices-report.md
- docs/lending/excel/overview.md
- docs/lending/guides/migration-guides/deprecation-account-categories.md
> Broken links fixes

- package-lock.json
- package.json
- src/theme/DocItem/index.tsx
> Add monitoring

- docs/using-the-api/webhooks/create-consumer.md
> Adding arcade example to webhooks

- docs/auth-flow/optimize/connection-management.md
- docs/bank-feeds/integrations/qbo/mapping.md
- docs/usecases/bill-pay/payments.md
Adding references to the Github examples for the Connections SDK.
> Connections SDK Github examples

- docs/expenses/sync-process/expense-transactions.md
> Update expense-transactions.md - adding adjustments

- docs/using-the-api/webhooks/migration-guide-advanced.md
Updating the IP list to include both IP's
> Update migration-guide with additional IP 

- docs/using-the-api/supplemental-data/overview.md
> Google Sheets styling fix

- docs/expenses/overview.md
- docs/expenses/sync-process/expense-transactions.md
- docs/expenses/sync-process/transfer-transactions.md
- docs/expenses/sync-process/uploading-receipts.md
- src/components/global/Integrations/integrations.js
> FreeAgent - Update.md

- docs/configure/user-management/user-roles.md
Updated the user role summary table. Switched The role `View company data` to `View company and integration data` to make it clear that viewing integration configuration can be done by anyone rather than developer or admin roles. 
Old:
New:
> updated user role table

- docs/expenses/sync-process/expense-transactions.md
> Tax Rates - Free Agent .md

- docs/smb-help-hub/integrations/qb-desktop/configure-connector.md
- docs/smb-help-hub/integrations/qb-desktop/install-connector.md
- docs/smb-help-hub/integrations/qb-desktop/overview.md
- docs/smb-help-hub/integrations/qb-desktop/troubleshooting.md
- sidebars/smb-help-hub.js
Initial links for QBD's help hub content
> QBD SMB Hub placeholder

- docs/using-the-api/supplemental-data/overview.md
add line about removing supplemental data config
added a sentence about how to reset supplemental data configuration.
> update supplemental data

- blog/240704-webhook-deprecation-extension.md
> Added extention notice to webhook deprecations

- blog/240220-qbd-sync-for-expenses.md
- blog/240227-qbd-connector.md
- blog/240314-new-bank-categorization.md
- blog/240316-reimbursable-expenses.md
- blog/240403-bill-pay-solution-kit.md
- blog/authors.yml
Adding 5 product updates to blog to backfill announcements from H1, ranging from February to April.
> Adding product updates to blog

- blog/authors.yml
> Adding myself to the internationally renown circle of Codat GitHub Authors

- blog/240220-qbd-sync-for-expenses.md
- docs/auth-flow/customize/customize-link.md
- docs/bank-feeds/overview.mdx
- docs/configure/portal/dashboard.mdx
- docs/get-started/first-steps.md
- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral.md
- docs/integrations/accounting/netsuite/accounting-netsuite.md
- docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
- docs/integrations/accounting/quickbooksdesktop/legacy/accounting-quickbooksdesktop.md
- docs/integrations/accounting/sage-intacct/accounting-sage-intacct-setup.md
- docs/integrations/accounting/sage50/accounting-sage50.md
- docs/using-the-api/queueing-data-syncs.md
- redirects.config.js
> Fix: removing Plans

- docs/using-the-api/querying.md
> Escape pipes

- docs/knowledge-base/advanced-sync-settings.md
> Readd advanced sync settings

- .env.example
- docusaurus.config.js
- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/TOC/Desktop/index.js
- src/theme/TOC/index.tsx
> Fixing edit url in theme

- docusaurus.config.js
> Fix social card

- docs/get-started/overview.md
- docs/index.mdx
- docs/support/get-help.mdx
- nav.config.js
- src/components/Clients/index.js
- src/components/Products/index.js
- src/components/ReadNext/index.js
- src/theme/NavbarItem/DropdownNavbarItem.js
> Cleanup console

- docs/auth-flow/overview.md
- docs/bank-feeds/overview.mdx
- docs/commerce/overview.md
- docs/expenses/overview.md
- docs/integrations/accounting/quickbooksdesktop/accounting-quickbooksdesktop.md
- docs/integrations/accounting/quickbooksdesktop/legacy/accounting-quickbooksdesktop.md
- docs/lending/get-started.md
- docs/lending/overview.md
- docs/payables/overview.mdx
- docs/supplier-enablement/overview.md
- docs/usecases/bill-pay/overview.md
- docs/usecases/summary/automating-payables.mdx
- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/Layout/useZendesk.js
> Re-add zendesk widget, fix classNames

- src/styles/components/_cards.scss
- src/styles/components/_google-sheets.scss
- src/styles/components/_table.scss
> Only de-indent elements at top level

- package-lock.json
- package.json
- src/components/Api/styles/stoplight.scss
- src/styles/components/_navbar.scss
> Bump stoplight

- docs/auth-flow/authorize-embedded-link.md
- docs/auth-flow/customize/sdk-customize-code.md
- docusaurus.config.js
- package-lock.json
- package.json
- src/styles/components/_doc-page.scss
- src/styles/components/_playground.scss
- src/styles/components/_search.scss
- src/styles/custom.scss
- src/theme/ReactLiveScope/index.js
- src/theme/ReactLiveScope/styles.module.scss
> fix search styling, maxwidth on page rows

- src/styles/components/_doc-sidebar.scss
> Fix sidebar collapse behaviour

- nav.config.js
- package.json
- src/components/Modal/styles.module.scss
- src/styles/components/_callout.scss
- src/styles/components/_read-next.scss
- src/styles/custom.scss
> Better colors for read next, esp. dark mode

- docs/get-started/first-steps.md
- docs/index.mdx
- docs/lending/features/accounts-payable-overview.md
- docs/lending/features/accounts-receivable-overview.md
- docs/lending/features/bank-statements-overview.md
- docs/lending/features/financial-statements-overview.md
- docs/lending/features/liabilities-overview.md
- docs/lending/features/sales-overview.md
- docs/lending/get-started.md
- docs/payables/get-started.md
- src/components/ClientLibraries/index.tsx
- src/components/Integrations/styles.module.scss
- src/components/Modal/styles.module.scss
- src/components/PageHeader/styles.module.scss
- src/styles/components/_article.scss
- src/styles/components/_doc-item.scss
- src/styles/components/_doc-page.scss
- src/styles/components/_labels.scss
- src/styles/components/_lists.scss
- src/styles/components/_search.scss
- src/styles/components/_toc.scss
- src/styles/custom.scss
- src/theme/DocItem/Layout/Vote/index.js
- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/Layout/styles.module.css
- src/theme/DocRoot/Layout/Main/styles.module.css
> Multiple formatting and content fixes

- docs/usecases/summary/managing-payroll.mdx
- docs/using-the-api/overview.md
- nav.config.js
- sidebars.js
- sidebars/products.js
- sidebars/usecases.js
- src/components/Products/index.js
- src/components/Usecases/index.js
Removing references to payroll
> Hide Payroll from site

- docs/expenses/config-and-categorize.md
> Dynamics - Supplier - Update config-and-categorize.md

- .gitattributes
- blog/240802-deprecation-old-qbd-integration.md
> Deprecation for legacy QBD blog post

- sidebars/sync-for-expenses.js
- FreeAgent is missing from the sidebar https://docs.codat.io/expenses/overview
- change order of integrations to alphabetical
> FreeAgent is missing from the sidebar for supported SfE integrations

- blog/240802-deprecation-old-qbd-integration.md
> Correcting date in title of QBD deprecation post

- docs/expenses/configure-customer.md
- missing Dynamics
- missing FreeAgent
- remove Sage Intacct
- order alphabetically
> fix integrations outlined on configure-customer.md

- sidebars/use-the-api.js
Updated sidebar to remove the legacy webhooks section
> Remove legacy webhooks

- blog/240227-qbd-connector.md
- blog/240802-deprecation-old-qbd-integration.md
- static/img/updates/240802-deprecation-old-qbd-integration-1.png
> Added new QBD screenshot to intro blog

- docs/using-the-api/webhooks/create-consumer.md
> Fix webhook verification code snippets

- src/components/PageHeader/styles.module.scss
- src/theme/DocRoot/Layout/Main/styles.module.css
> Fix overflow behaviour

- docs/supplier-enablement/guides/analyze-spend.md
- docs/supplier-enablement/guides/manage-relationships.md
- docs/supplier-enablement/guides/refresh-data.md
- docs/supplier-enablement/resources/customer-faqs.md
- sidebars/supplier-enablement.js
- src/components/Questions/styles.module.scss
- src/styles/components/_read-next.scss
> Supplier enablement rework

- src/components/Integrations/integrations.js
> Add Oracle NetSuite to supported BPK integrations

- docs/lending/features/accounts-payable-overview.md
- docs/lending/features/accounts-receivable-overview.md
- docs/lending/features/bank-statements-overview.md
- docs/lending/features/company-info-overview.md
- docs/lending/features/financial-statements-overview.md
- docs/lending/features/liabilities-overview.md
- docs/lending/features/sales-overview.md
- docs/using-the-api/custom-data.md
- docs/using-the-api/supplemental-data/overview.md
> Fixing embedded spreadsheets

- nav.config.js
> Adding bill pay kit OAS

- docs/using-the-api/rate-limits.md
> Fixed rate limits

- docusaurus.config.js
- package-lock.json
- package.json
> Image zoom

- docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-faq.md
- static/img/integrations/accounting/quickbooksdesktop/read-history-fetching-waiting-for-async-response.png
> added-to-faq-draft

- .github/workflows/oas-sitemap.yml
- package.json
- src/utils/oas-sitemap.js
> Adding sitemap

- docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-faq.md
- docs/integrations/accounting/sage200/accounting-sage200-setup.md
> draft update to QBD FAQ

- blog/230217-uat-deprecation-dns.md
- docs/configure/user-management/user-roles.md
> Clearer roles info

- docs/smb-help-hub/integrations/sage-50/troubleshooting.md
> Fixing typo in the last section

- docs/using-the-api/push.md
- docs/using-the-api/webhooks/event-types.md
> Moved lottie pic

- docs/lending/features/company-info-overview.md
Python example does not work
- Missing mandatory keyword argument 'request' in method call PylintE1125:missing-kwoa
- Undefined variable 'req' PylintE0602:undefined-variable
> Update Python example for lending/features/company-info-overview

- src/components/CodatLink/index.js
- src/components/CodatLink/styles.module.scss
> Add a responsive modal to link sdk

- src/styles/components/_lists.scss
> Fix OL elements wrapping to new lines

- docs/auth-flow/authorize-embedded-link.md
- docs/auth-flow/optimize/connection-management.md
- docs/core-concepts/connections.md
- src/components/Api/styles/stoplight.scss
- src/styles/components/_admonitions.scss
- src/styles/components/_cards.scss
- src/styles/components/_code.scss
- src/styles/components/_images.scss
- src/styles/components/_links.scss
- src/styles/components/_markdown.scss
- src/styles/components/_tabs.scss
- src/styles/custom.scss
> Improve styles, various

- docs/get-started/overview.md
- src/components/Cards/index.js
- src/styles/components/_cards.scss
- src/styles/components/_links.scss
> Adding a card component, various restyling of links, etc.

- src/components/Api/styles/stoplight.scss
> Fixed styling issue

- blog/241030-new-connection-failed-webhook.md
- docs/using-the-api/webhooks/event-types.md
> Added connection event type

- docs/using-the-api/webhooks/migrating-to-new-event-types.md
Updating the example from Successful to Success
> Correcting status of write.successful response

- docs/enterprise/tech-overview/security/sso.md
Small update to the URL specified which helps clients to configure SSO.
> Update to the URLs specified for client config

- docs/auth-flow/authorize-embedded-link.md
- docs/auth-flow/optimize/connection-management.md
- docs/auth-flow/overview.md
- docs/get-started/accounting-for-beginners.md
- docs/integrations/accounting/overview.md
- docs/integrations/accounting/sage200/accounting-sage200-setup.md
- docs/integrations/accounting/sage200/accounting-sage200.md
- docs/integrations/accounting/sage200/sage200-limitations.md
- redirects.config.js
- sidebars/integrations-accounting.js
- src/components/Integrations/integrations.js
> Change Sage 200cloud to Sage 200 Standard

- docs/integrations/accounting/sage200/sage200-limitations.md
> Add Sage 200 limitation for invoices

- blog/241120-onconnectionstarted-.md
- blog/241120-onconnectionstarted.md
- static/img/link/integration_selection.png
> blog post onconnectionstarted

- src/components/Lottie/index.js
> Fix lottie

- blog/241125-filter-companies-by-tags.md
- docs/using-the-api/managing-companies.md
> Added filter companies by tags

- blog/241004-deprecation-bank-feed-source-account-event-types.md
> Fixed old schema def

- docs/integrations/accounting/xero/partner-certification/checkpoints-app-store.md
Remove references to unlink connection endpoint as per recent Xero feedback
Remove references to unlink connection endpoint following Xero feedback
> Update checkpoints-app-store_remove references to unlink connection.md

- docs/integrations/accounting/xero/partner-certification/checkpoints-AP-Payments.md
Remove references to unlink connection endpoint following Xero feedback
> Update checkpoints-AP-Payments remove references to Unlink endpoint.md

- docs/integrations/accounting/exact-online/accounting-exact-setup.md
Bank Feeds product requires slightly different scopes, adding this nuance to Access Level column of the table detailing the scopes to set during setup.
> Update accounting-exact-setup.md for Bank Feeds

- docs/enterprise/banks/overview.md
- docs/get-started/overview.md
- docs/support/get-help.mdx
- src/pages/support/index.tsx
> Remove Cochat references

- blog/250129-webhook-transformations.md
- docs/using-the-api/webhooks/create-consumer.md
- static/img/use-the-api/webhooks-transformation-edit.png
- static/img/use-the-api/webhooks-transformation-example.png
- static/img/use-the-api/webhooks-transformation-menu.png
> Product updates webhook transformations

- blog/250131-shopify-update.md
> Shopify update

- blog/240403-bill-pay-solution-kit.md
- docs/payables/async/suppliers.md
- docs/payables/configure-customer.md
- docs/payables/get-started.md
- docs/payables/sync/suppliers.md
> Fix broken links

- package-lock.json
- package.json
- src/theme/DocPage/index.tsx
> Removing hotjar

- blog/240204-new-product-docs.md
- blog/250204-new-product-docs.md
Blog post to announce name and structure changes
> Blog post re: names and structure

- docs/auth-flow/authorize-embedded-link.md
- docs/auth-flow/authorize-hosted-link.md
- docs/auth-flow/build/build-your-own-authorization-journey.md
- docs/auth-flow/optimize/connection-management.md
Adding OTP information to various Link docs.
> Fix Link docs for OTP

- blog/250204-new-product-docs.md
- docs/index.mdx
- docs/supplier-enablement/get-started.md
- docs/supplier-enablement/guides/manage-relationships.md
- docs/supplier-enablement/guides/refresh-data.md
- docs/supplier-enablement/overview.md
- docs/supplier-enablement/resources/customer-faqs.md
- docs/usecases/summary/spend-insights.md
- docs/using-the-api/webhooks/event-types.md
- nav.config.js
- sidebars.js
- sidebars/products.js
- sidebars/spend-insights.js
- src/components/Integrations/integrations.js
- src/components/Products/index.js
- src/pages/supplier-enablement-api/index.tsx
Docs infrastructure and homepage changes to rename SE to SI
> SE to SI name changes

- docs/bank-feeds/integrations/qbo/mapping.md
Theres no numbered steps on this page so this is confusing
> Removed 'see step six in the next procedure'

- sidebars/products.js
> Adding a section title... looks weird without one

- blog/250219-qbo-minor-versions-update.md
> Added update on QBO minor versions deprecation

- docs/using-the-api/get-data-troubleshooting.md
- sidebars/use-the-api.js
> Added troubleshooting get data docs

- docs/expenses/sync-process/expense-transactions.md
- docs/expenses/sync-process/reimbursable-expense-transactions.md
update default tax rates on SfE docs
> add zoho books default tax rate to expense-transactions.md

- docs/integrations/accounting/netsuite/oracle-netsuite-integration-reference.md
- docs/integrations/accounting/zoho-books/zoho-book-limits.md
Content corrections for a number of Lending tickets
> Lending ticket fixes

- blog/250401-bank-feeds-connections.md
- static/img/updates/250401-bank-feeds-connections.png
New product update for Bank Feeds mapping UI
> Blog: Bank Feeds mapping UI

- blog/250404-deprecation-d365-jes-basecurrency.md
- blog/250404-deprecation-netsuite-je-basecurrency.md
- blog/250404-update-accounts-balances.md
- blog/authors.yml
* Deprecation - change the way we map JEs for NetSuite. Now they would be mapped in base currency
* Product update - account balances work we have been doing for Lloyds
> Product update and deprecation announcement

- docs/configure/user-management/user-roles.md
Adding a row to the permissions table to split connection management permissions
> correct user permissions table

- docs/integrations/accounting/quickbooksdesktop/quickbooks-desktop-faq.md
Adding an FAQ to clarify batching on financial report datatypes
> add FAQ for QBD report batching

- docs/bank-feeds/bank-feeds-sdk.md
Updates to the Bank Feeds SDK process flow steps
> Bank Feeds SDK updates

- docs/auth-flow/customize/customize-link.md
- docs/auth-flow/customize/sdk-customize-code.md
- static/img/auth-flow/multi-entity-setting-off-on.png
Adding ability to toggle multi-entity support, also rewording and moving the "retries" setting.
> Update Link settings docs to surface multi-entity support

- docs/bank-feeds/integrations/sage/mapping.md
- docs/integrations/bank-feeds/sage-bank-feeds/sage-bank-feeds-authenticate-users-web-app.md
- static/img/integrations/accounting/sage-mapping-redirect-screen.png
> Fix sage img

- docs/integrations/bank-feeds/sage-bank-feeds/sage-bank-feeds-authenticate-users-web-app.md
Fix issue in request body to align with instruction
> Update sage-bank-feeds-authenticate-users-web-app - fix issue in request body to align with instruction

- docs/lending/overview.md
- src/components/Integrations/integrations.js
> Added lending integrations filter to remove Workday

- blog/250603-intuit-partner-program-changes.md
> Intuit parnerships post

- .github/scripts/generate_oas_changelog.py
- .github/workflows/oas-changelog.yml
> Adding changelog action

- .github/scripts/generate_oas_changelog.py
> Adding links to oas changelogs

- sidebars/spend-insights.js
- src/components/Integrations/integrations.js
> Format fix

- .github/workflows/markdown-lint.yml
- .markdownlint.json
- package-lock.json
- package.json
> Add markdown lint

- docs/expenses/sync-process/transfer-transactions.md
Update docs to link to OAS to display supported integrations for both create and update - previously this was unclear. 
> FOR-51 Update transfer transactions to link to OAS

- docs/enterprise/tech-overview/security/sso.md
Updating the content on the SSO setup page to help clients. 
Current:
New:
> ATH-200 SSO Page Update

- .github/workflows/linknator.yml
> Make link checking more efficient

- docs/integrations/accounting/sage50/accounting-sage50.md
- docs/integrations/accounting/sage50/installing-the-sage-50-connector.md
- docs/integrations/accounting/sage50/pushing-data-to-sage-50.md
- docs/integrations/accounting/sage50/restart-the-sage-50-connector.md
- docs/integrations/accounting/sage50/sage-50-requirements.md
- docs/integrations/accounting/sage50/sage50-multi-company-mode.md
- docs/integrations/accounting/sage50/sage50-troubleshooting.md
- docs/integrations/accounting/sage50/uninstalling-the-sage-50-connector.md
- src/components/Integrations/integrations.js
> Sage 50 accvounts

- src/components/DataTypes/index.js
Fixing the search to account for null values
> changing search to account for null title, key or descriptions

- docs/integrations/banking/overview.md
Adding banking platform keys to documents to ensure users can create these via the API
> add banking platform keys

- blog/250807-deprecation-relaxed-removal-of-company-product-assignment.md
> Added deprecation notice for company-product assignment

- blog/250815-connection-management-sdk-updated-landing-page-title.md
- static/img/updates/2025-08-15-connection-management-title-change.png
> Added connection management title change update
