- sidebars/banking-api.js
- sidebars/commerce-api.js
- sidebars/integrations.js
Fixes #74 
Also fixes a couple of broken links from the Banking API and Commerce API homepages, which were missing the initial `/`s.
> Sidebar fixes: Add on-prem connector setup and fix links from 2 API product pages

- sidebars/dataModel.js
"Bank transaction" does not seem to exist anymore and leads to the Acctg API reference main page
> Update dataModel.js nav

- blog/230411-api-keys.md
- blog/230411-deletion-of-data.md
- blog/230411-legacy-bank-account-endpoints.md
Hey Team - I see that we've updated the [legacy bank endpoints deprecation date](https://docs.codat.io/updates/230411-legacy-bank-account-endpoints) to April 11th but in the body in the first paragraph it still shows April 10th!
> changelog - apr 10 date fixes

- blog/230710-deprecation-bankaccount-banktransaction.md
Deprecation of the shared use of bankAccount and bankTransaction datatypes for banking data connections.
> Add new change log entry for deprecating shared use of old accounting datatypes

- docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds.md
Fixes a broken link to the Banking Service docs and reformats the link to Markdown.
Also fixes two more links to the API reference.
> Sage Bank Feeds links

- docs/integrations/accounting/freeagent/freeagent-integration-reference.md
This pull request documents some caveats around pushing Direct costs to FreeAgent via our integration. It also aligns the existing text for Direct incomes to match.
Also removes some of the old link styling.
> Freeagent - Add call-outs for pushing Direct costs

- src/components/global/Api/index.css
- Currently the deprecation badge isn't visible, causing confusion. Only hiding the v1.X badge now.
- Increase contrast on examples dropdown
- Border-radius updates throughout
- Add correct cursor behaviour to API call button
> Various API ref styling fixes

- vercel.json
Previous change didn't fix CORS issues. I think this is because it won't allow Datadog headers to be set, so we need to add these to the vercel config.
> Allow Datadog headers

- docs/bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-setup.md
- docs/bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup.md
Small changes to remove references to PUT /bankAccounts and creating multiple accounts to make it consistent with deprecation notice.
- /bank-feeds-api/sage-bank-feeds/sage-bank-feeds-setup
- /bank-feeds-api/qbo-bank-feeds/qbo-bank-feeds-setup
> removed references to PUT /bankAccounts

- docs/integrations/commerce/bigcommerce/commerce-bigcommerce-integration-reference.md
Order transactions paging doesn't work on bigcommerce so we have the max page size set but if this limit is breached by the data in bigcommerce we're not able to fetch it.
> Calling out limits on BigCommerce API

- docs/auth-flow/authorize-embedded-link.md
Update the links that go to https://github.com/codatio/sdk-link/tree/main/examples/{language}/* to https://github.com/codatio/sdk-link/tree/main/examples/languages/{language}/*
> Fix links in authorize-embedded-link.md

- docs/bank-feeds/create-account.md
- docs/bank-feeds/setup.md
> Bank Feeds implementation feedback

- docs/using-the-api/rate-limits.md
/using-the-api/rate-limits
- Making daily reset of rate limits more visible
- Adding the same detail to the example 1 calculation
- Referencing the client rate limit webhook
- Adding a Read next section
> Rate limits - daily reset

- docs/configure/portal/developers.md
- docs/using-the-api/authentication.md
- docs/using-the-api/best-practices/client-side-data-storage.md
- docs/using-the-api/best-practices/implementing-a-mapping-page.md
- docs/using-the-api/modified-dates.md
- docs/using-the-api/optimizing-api-calls.md
- docs/using-the-api/ordering-results.md
- sidebars/use-the-api.js
Changes to the Using the API navigation structure
> Using the API menu reorg

- src/components/global/ClientLibraries/index.tsx
Our language tiles now partially support displaying the latest version of the library for a given product. This works for c#, typescript and python. I need to work out how this is done for go and once Java is deployed finalise support for java. This change will help clients, support and implementations in understanding the latest versions of our packages.
Feel free to 'Enable automerge' - …
> Added library latest version to langauge cards in c#, typescript and python as well as prepped go and java

- docs/using-the-api/webhooks/create-consumer.md
- docs/using-the-api/webhooks/event-types.md
- docs/using-the-api/webhooks/overview.md
- sidebars/use-the-api.js
> Minor changes to webhooks docs

- docs/expenses/sync-process/expense-transactions.md
- docs/expenses/sync-process/reimbursable-expense-transactions.md
Push body for expense transactions using new create expense transaction was incorrect (included 'items' field) and also didn't include the bankAccountRef field. 
> Removed items, added bankAccountRef

- docs/configure/user-management/user-roles.md
Updating the user tole table define that any user role can upload data to the company. 
Existing role definitions:
New role definitions:
> Update role table for uploading data

- docs/expenses/sync-process/uploading-receipts.md
Just had a ticket with Xero Support and they mentioned their accounting API file attachment upload limit is actually 3 MB, (so one less than what's listed here).
- updating existing
> Updating Attachment Advice for Xero limit

- docs/integrations/accounting/dynamics365businesscentral/accounting-dynamics365businesscentral.md
- docs/integrations/accounting/sage200/accounting-sage200.md
- docs/integrations/accounting/sage50/sage-50-requirements.md
> Added support variations for Dynamics, Sage 50 and 200

- docs/integrations/accounting/xero/partner-certification/checkpoints-bank-feeds.md
Update link to bank feed specific company info
Update link to bank feed specific company info
> Update link to bank feed specific company info

- docs/auth-flow/customize/sdk-customize-code.md
> Add enableMultiEntityLinking option

- .github/workflows/codereviews.yml
- .github/workflows/linknator.yml
> Tweak code reviewer

- blog/241120-onconnectionstarted.md
- blog/241124-bank-feeds-sdk.md
- src/styles/components/_images.scss
- static/img/updates/bank-feeds-bento.png
> Bank feeds sdk update

- docs/lending/guides/loan-writeback/configure.md
As explained by @rmarcall the account is created automatically but apparently not immediately.
> The approach is a generic approach related to our implementation for POSTing bank account mappings, in that we're not waiting anywhere in the background to update it, but deferring until the next "operation" (GET mapping/Push bank transactions). Given the webhook will only be sent when you invoke that next action my recommendation would be to hit the GET endpoint after you POST, to retrieve the TargetAccountId property and if there is an error due to a failure on the Xero side handle that then. Using this flow means you don't need to rely on the webhook either
⚠️ Feel free to edit what I've written, the PR is just to get the idea across. You might even want to add another step with a code …
> Update docs to clarify when bank feeds account is created

- nav.config.js
Removing the menu link to twitter - at some point codat has seemingly given up our twitter account and it has now been registered by a security researcher. As a result it is uncontrolled and we should remove all references to it
**Existing**
**Update**
> Remove twitter link

- code_utils/code_finder.py
- code_utils/docker/.dockerignore
- code_utils/docker/CodatSnippets.csproj
- code_utils/docker/Dockerfile
- code_utils/docker/build.bat
- code_utils/docker/build.sh
- code_utils/docker/package.json
- code_utils/docker/requirements.txt
- code_utils/docker/tsconfig.json
- I have updated the logic of the extract_code_from_files script, so that it separates the extracted files into complete and incomplete, based on whether or not we can resonably expect the code within the file to run in a self-contained manner
- I have a docker file which builds a container with Python, .NET Core and TypeScript installed.
- The Dockerfile copies the _complete_ code files into a corresponding project directory in the Container. 
- The Dockerfile then uses the following files to install dependencies including the Codat client SDKs for each lang:
- - requirements.txt (for Python)
- - tsconfig.json (for Typescript)
- - CodeSnippets.csproj (For C#) 
**NEXT STEPS**
Now we can extract all complete code snippets from the docs and copy them to a container with all the dependencies …
> Adding Dockerfile to the code_utils

- code_utils/README.md
- code_utils/check_extracted_code.py
- code_utils/code_checker.py
- code_utils/docker/Dockerfile
- code_utils/docker/tsconfig.json
- code_utils/docker/validate-csharp-snippets.sh
This is the first iteration of a Python utility which actually checks the correctness of the doc's code snippets. 
The code_utils folder now contains two scripts:
- One to pull out all code snippets and divide them into _complete_ and _incomplete_
- One to build a container containing all necessary dependencies and attempt to compile* ** the complete scripts
* compile for Python means use `pyright` (which powers VS Code's Python Language server... a.k.a puts the squiggly red lines in the IDE editor when the code is wrong). 
** .NET's project based nature doesn't lend itself well to self contained scripts, or at least not compiling a lot of self contained scripts as part of a single project. [validate-csharp-snippets.sh](https://github.com/codatio/codat-docs/compare/main...adding-actual-che …
> Adding Script To Check Code Snippets
